<?php

/** Status do Curso */
define('CURSO_ESTADO_ANDAMENTO', 'ANDAMENTO');
define('CURSO_ESTADO_CANCELADO', 'CANCELADO');
define('CURSO_ESTADO_CONCLUIDO', 'CONCLUIDO');

/** Tipo do Curso */
define('CURSO_TIPO_CURSO', 'CURSO');
define('CURSO_TIPO_PRECEPTORIA', 'PRECEPTORIA');

/** Tipo da Matricula */
define('MATRICULA_TIPO_INSCRITO', 'INSCRITO');
define('MATRICULA_TIPO_CONCLUIDO', 'CONCLUIDO');
define('MATRICULA_TIPO_DESISTENCIA', 'DESISTENCIA');
define('MATRICULA_TIPO_INCOMPLETO', 'INCOMPLETO');
define('MATRICULA_TIPO_REPOSICAO', 'REPOSICAO');

/** Tipo do Aluno */
define('ALUNO_TIPO_ALUNO', 'ALUNO');
define('ALUNO_TIPO_MONITOR', 'MONITOR');

/** Estado Civil */
define('ESTADO_CIVIL_SOLTEIRO', 'SOLTEIRO');
define('ESTADO_CIVIL_CASADO', 'CASADO');
define('ESTADO_CIVIL_DIVORCIADO', 'DIVORCIADO');
define('ESTADO_CIVIL_VIUVO', 'VIUVO');
define('ESTADO_CIVIL_SEPARADO', 'SEPARADO');

/** SIGNOS */
define('SIGNO_AQUARIO', 'AQUARIO');
define('SIGNO_PEIXES', 'PEIXES');
define('SIGNO_ARIES', 'ARIES');
define('SIGNO_TOURO', 'TOURO');
define('SIGNO_GEMEOS', 'GEMEOS');
define('SIGNO_CANCER', 'CANCER');
define('SIGNO_LEAO', 'LEAO');
define('SIGNO_VIRGEM', 'VIRGEM');
define('SIGNO_LIBRA', 'LIBRA');
define('SIGNO_ESCORPIAO', 'ESCORPIAO');
define('SIGNO_SAGITARIO', 'SAGITARIO');
define('SIGNO_CAPRICORNIO', 'CAPRICORNIO');
